services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: example
            POSTGRES_PASSWORD: example
            POSTGRES_DB: exampledb
        ports:
            - "5432:5432"

    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: exampledb
            MYSQL_USER: example
            MYSQL_PASSWORD: example
        ports:
            - "3306:3306"

    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: exampledb
            MYSQL_USER: example
            MYSQL_PASSWORD: example
        ports:
            - "3307:3306"
    adminer:
        image: adminer:latest
        ports:
            - "8080:8080"
